module.exports = {
	
	'EMP_MASTER'    							    : 'MIS_EMP_MASTER',
	'EMP_EDU' 			     			        	: 'MIS_EMP_EDU',
	'EMP_WORKEXP' 		     				    	: 'MIS_EMP_WORKEXP',
	'EMP_PAY_STRUCT' 	    						: 'MIS_EMP_PAY_STRUCT',
	'EMP_KYC_DETAIL' 	    						: 'MIS_EMP_KYC_DETAIL',
	'EMP_MGR_DETAIL' 	    						: 'MIS_EMP_MGR_DETAIL', 
	'USER_MASTER'   								: 'MIS_USER',
	'USER_ACCESS_LEVELS' 							: 'MIS_USER_ACCESS_LEVEL',
	'LMS_RULE'   									: 'MIS_LMS_RULE',
    'HOLIDAY_LIST'            						: 'MIS_HOLIDAY_LIST',
    'LMS_MASTER'            						: 'MIS_LMS_MASTER',
    'LMS_LEAVE_APPLY'      							: 'MIS_EMP_LEAVE_APPLY',
	'LMS_LEAVE_AVAIL'  								: 'MIS_EMP_LMS_AVAIL',
    'VARCHAR25'                                     : 'VarChar(25)',
    'VARCHAR15'                                     : 'VarChar(15)',
	'VARCHAR50' 									: 'VarChar(50)',
    'VARCHAR100' 									: 'VarChar(100)',
    'VARCHAR20'   									: 'VarChar(20)',
    'VARCHAR2'   									: 'VarChar(2)',
    'VARCHAR5'   									: 'VarChar(5)',
    'VARCHAR8'                                      : 'VarChar(8)',
    'VARCHAR1'   									: 'VarChar(1)',
    'VARCHAR70'                                     : 'VarChar(70)',
    'INT'        									: 'Int',
    'BIT'        									: 'Bit',
    'SMINT'      									: 'Smallint',
    'DEC_10_6'   									: 'decimal(10, 6)',
    'DATE_TIME'  									: 'DATETIME',
    'DATE_TYPE'                                     : 'DATETYPE',
   	'VARCHAR255'                                    : 'VarChar(255)',
    'ACTIVE_STATUS'                                 : 'ACTIVE'
	
};